web-console/README.md, web-console/package.json, web-console/script/build, web-console/script/watch, web-console/src/components/auto-form.tsx, web-console/src/components/header-bar.tsx, web-console/src/components/rule-editor.scss, web-console/src/components/rule-editor.tsx, web-console/src/console-application.tsx, web-console/src/dialogs/retention-dialog.scss, web-console/src/dialogs/retention-dialog.tsx, web-console/src/dialogs/runtime-property-dialog.tsx, web-console/src/entry.ts, web-console/src/views/data-source-view.tsx, web-console/src/views/home-view.tsx, web-console/src/views/segments-view.tsx, web-console/src/views/servers-view.tsx, web-console/src/views/sql-view.tsx, web-console/src/views/tasks-view.tsx, web-console/webpack.config.js
=> Retention rules edition

web-console/src/components/header-bar.tsx, web-console/src/console-application.tsx, web-console/src/views/home-view.tsx, web-console/src/views/property-status-view.tsx, web-console/src/views/property-view.scss, web-console/src/views/property-view.tsx
- Allows home view tiles to reflect the real number of datasources, segments, etc..
- Changed config to popover to enable more tabs
- Added druid status property
=> Console editing

web-console/src/dialogs/post-spec-dialog.tsx, web-console/src/views/tasks-view.tsx
- More generalized post spec dialog
=> Console post spec edit

extensions-core/kinesis-indexing-service/pom.xml, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisIndexTask.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisIndexingServiceModule.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisSamplerSpec.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisorSpec.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisIndexTaskSerdeTest.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisIndexTaskTest.java
Backport of https://github.com/apache/druid/pull/9058 to 0.17.0-iap.
=> [Backport] Get proper Kinesis index task AWS credentials (#9082)

extensions-contrib/distinctcount/src/test/java/org/apache/druid/query/aggregation/distinctcount/DistinctCountGroupByQueryTest.java
Backport of upstream PR 9120 to 0.16.0-iap.
=> [Backport] Fix DistinctCountGroupByQueryTest Y2020 bug.

extensions-core/parquet-extensions/pom.xml
Backport of apache/druid#9124 to 0.17.0-iap
=> [Backport] Add avro dependency to parquet extension

.idea/mavenProjectSettings.xml, extensions-core/s3-extensions/pom.xml, extensions-core/s3-extensions/src/main/java/org/apache/druid/firehose/s3/StaticS3FirehoseFactory.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/ObjectSummaryIterator.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3TimestampVersionedDataFinder.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3Utils.java, extensions-core/s3-extensions/src/test/java/org/apache/druid/storage/s3/ObjectSummaryIteratorTest.java
Backport of apache/druid#9098 to 0.16.0-iap.
=> [Backport] S3: Improvements to prefix listing (including fix for an infinite loop)

owasp-dependency-check-suppressions.xml
Backport https://github.com/apache/druid/pull/9189 to 0.17.0-iap
=> [Backport] Suppress CVE-2019-20330 for htrace-core-4.0.1 (#9189)

extensions-core/hdfs-storage/pom.xml
Backport https://github.com/apache/druid/pull/9178 to 0.17.0-iap
=> Add jackson-mapper-asl for hdfs-storage extension (#9178)

core/src/main/java/org/apache/druid/data/input/TextReader.java, core/src/main/java/org/apache/druid/data/input/impl/CsvInputFormat.java, core/src/main/java/org/apache/druid/data/input/impl/DelimitedInputFormat.java, core/src/main/java/org/apache/druid/data/input/impl/DelimitedValueReader.java, core/src/main/java/org/apache/druid/data/input/impl/FlatTextInputFormat.java, core/src/main/java/org/apache/druid/data/input/impl/JsonInputFormat.java, core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java, core/src/main/java/org/apache/druid/data/input/impl/RegexInputFormat.java, core/src/main/java/org/apache/druid/data/input/impl/RegexReader.java, core/src/main/java/org/apache/druid/java/util/common/parsers/CSVParser.java, core/src/main/java/org/apache/druid/java/util/common/parsers/DelimitedParser.java, core/src/test/java/org/apache/druid/data/input/impl/CsvInputFormatTest.java, core/src/test/java/org/apache/druid/data/input/impl/DelimitedInputFormatTest.java, core/src/test/java/org/apache/druid/data/input/impl/DelimitedReaderTest.java
Backport of #9199 to 0.17.0-iap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/implydata/druid/41)
=> [Backport] Fix TSV bugs

extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authorization/db/cache/CoordinatorPollingBasicAuthorizerCacheManager.java
Backport of #9354 to 0.17.0-iap
=> Fix basic auth polling to skip retries when cachedSerializedGroupMappingMap returns 404 (#9354)

examples/bin/java-util, examples/bin/verify-java
Backport https://github.com/apache/druid/pull/9376 to 0.17.0-iap
=> [Backport] Make java version check work on all shells (#9376)

docs/development/extensions-core/s3.md, docs/ingestion/native-batch.md, extensions-core/s3-extensions/src/main/java/org/apache/druid/data/input/s3/S3InputSource.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/data/input/s3/S3InputSourceConfig.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3StorageDruidModule.java, extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/ServerSideEncryptingAmazonS3.java, extensions-core/s3-extensions/src/test/java/org/apache/druid/data/input/s3/S3InputSourceTest.java, extensions-core/s3-extensions/src/test/java/org/apache/druid/storage/s3/TestAWSCredentialsProvider.java, website/.spelling
Manually resolve merge conflict in
S3InputSource.java
S3InputSourceTest.java
=> [Backport] Add support for optional aws credentials for s3 for ingestion

benchmarks/src/test/java/org/apache/druid/benchmark/ExpressionFilterBenchmark.java, core/src/main/java/org/apache/druid/math/expr/Function.java, docs/querying/filters.md, processing/src/main/java/org/apache/druid/segment/filter/InFilter.java, processing/src/test/java/org/apache/druid/segment/filter/InFilterTest.java, sql/src/main/java/org/apache/druid/sql/calcite/expression/AliasedOperatorConversion.java, sql/src/main/java/org/apache/druid/sql/calcite/expression/builtin/ArrayContainsOperatorConversion.java, sql/src/main/java/org/apache/druid/sql/calcite/expression/builtin/ArrayOverlapOperatorConversion.java, sql/src/main/java/org/apache/druid/sql/calcite/expression/builtin/BaseExpressionDimFilterOperatorConversion.java, sql/src/main/java/org/apache/druid/sql/calcite/planner/PlannerFactory.java, sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java
Backport of #9487 to 0.17.0-iap. This is a clean backport.
=> [Backport] Convert array_contains() and array_overlaps() into native filters if possible

benchmarks/src/main/java/org/apache/druid/timeline/VersionedIntervalTimelineBenchmark.java, core/pom.xml, core/src/main/java/org/apache/druid/timeline/VersionedIntervalTimeline.java, core/src/main/java/org/apache/druid/timeline/partition/AtomicUpdateGroup.java, core/src/main/java/org/apache/druid/timeline/partition/ImmutablePartitionHolder.java, core/src/main/java/org/apache/druid/timeline/partition/OvershadowableManager.java, core/src/main/java/org/apache/druid/timeline/partition/PartitionHolder.java, core/src/test/java/org/apache/druid/timeline/VersionedIntervalTimelineSpecificDataTest.java, core/src/test/java/org/apache/druid/timeline/VersionedIntervalTimelineTest.java, core/src/test/java/org/apache/druid/timeline/VersionedIntervalTimelineTestBase.java, core/src/test/java/org/apache/druid/timeline/partition/AtomicUpdateGroupTest.java, core/src/test/java/org/apache/druid/timeline/partition/OvershadowableManagerTest.java, indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/SinglePhaseSubTask.java, indexing-service/src/main/java/org/apache/druid/indexing/input/DruidInputSource.java, indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/SinglePhaseParallelIndexingTest.java, integration-tests/src/test/java/org/apache/druid/tests/indexer/AbstractITBatchIndexTest.java, server/src/main/java/org/apache/druid/client/DataSourcesSnapshot.java, server/src/main/java/org/apache/druid/metadata/IndexerSQLMetadataStorageCoordinator.java, server/src/main/java/org/apache/druid/server/coordinator/helper/NewestSegmentFirstIterator.java, server/src/test/java/org/apache/druid/server/coordinator/helper/DruidCoordinatorSegmentCompactorTest.java
Backport of #9441 to 0.17.0-iap.
=> [Backport] Improve OvershadowableManager performance

server/src/main/java/org/apache/druid/client/indexing/HttpIndexingServiceClient.java, server/src/main/java/org/apache/druid/server/coordinator/helper/NewestSegmentFirstIterator.java, server/src/test/java/org/apache/druid/server/coordinator/helper/DruidCoordinatorSegmentCompactorTest.java
Backport of #9535 to 0.17.0-iap.
=> [Backport] Fix UnsupportedOperationException when sorting segments in auto compaction

indexing-service/src/main/java/org/apache/druid/indexing/input/DruidSegmentReader.java, integration-tests/README.md, integration-tests/quickstart-it.json, integration-tests/src/test/java/org/apache/druid/tests/indexer/ITCompactionTaskTest.java, integration-tests/src/test/java/org/apache/druid/tests/indexer/ITIndexerTest.java, integration-tests/src/test/resources/indexer/wikipedia_reindex_druid_input_source_task.json, integration-tests/src/test/resources/indexer/wikipedia_with_timestamp_index_task.json
=> DruidSegmentReader should work if timestamp is specified as a dimension (#9530)

server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java, server/src/main/java/org/apache/druid/guice/CoordinatorDiscoveryModule.java, server/src/main/java/org/apache/druid/guice/IndexingServiceDiscoveryModule.java, server/src/test/java/org/apache/druid/discovery/DruidLeaderClientTest.java, server/src/test/java/org/apache/druid/server/coordinator/duty/CompactSegmentsTest.java, sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java
This reverts commit 072bbe210f162228e85391b464f114da448df24a due to bug discovered during multi-master deployment.
See https://github.com/apache/druid/issues/9701
=> Revert apache#9481

processing/src/main/java/org/apache/druid/segment/DimensionHandler.java, processing/src/main/java/org/apache/druid/segment/DimensionIndexer.java, processing/src/main/java/org/apache/druid/segment/StringDimensionHandler.java, processing/src/main/java/org/apache/druid/segment/StringDimensionIndexer.java, processing/src/test/java/org/apache/druid/segment/IndexMergerNullHandlingTest.java, processing/src/test/java/org/apache/druid/segment/IndexMergerTestBase.java, processing/src/test/java/org/apache/druid/segment/incremental/IncrementalIndexRowCompTest.java
Backport of #9742 to 0.17.0-iap
=> [BACKPORT 0.17.0-iap] Adjust string comparators used for ingestion (#9742)

processing/src/main/java/org/apache/druid/segment/DimensionHandler.java, processing/src/main/java/org/apache/druid/segment/DimensionIndexer.java, processing/src/main/java/org/apache/druid/segment/StringDimensionHandler.java, processing/src/main/java/org/apache/druid/segment/StringDimensionIndexer.java, processing/src/test/java/org/apache/druid/segment/IndexMergerNullHandlingTest.java, processing/src/test/java/org/apache/druid/segment/IndexMergerTestBase.java, processing/src/test/java/org/apache/druid/segment/incremental/IncrementalIndexRowCompTest.java
Backport of #9742 to 0.18.0-iap
=> [BACKPORT 0.18.0-iap] Adjust string comparators used for ingestion (#9742)

extensions-core/kafka-indexing-service/src/main/java/org/apache/druid/indexing/kafka/supervisor/KafkaSupervisor.java, extensions-core/kafka-indexing-service/src/main/java/org/apache/druid/indexing/kafka/supervisor/KafkaSupervisorReportPayload.java, extensions-core/kafka-indexing-service/src/main/java/org/apache/druid/indexing/kafka/supervisor/KafkaSupervisorTuningConfig.java, extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/supervisor/KafkaSupervisorTest.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplier.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisor.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisorReportPayload.java, extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisorTuningConfig.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisIndexTaskTest.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisIndexTaskTuningConfigTest.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplierTest.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisorTest.java, indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java, indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorReportPayload.java, indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorTuningConfig.java, indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/TaskReportData.java, indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorStateTest.java
This PR reverts https://github.com/apache/druid/pull/9509.
=> Rollback kinesis lag metric for 0.18.1-iap

core/src/main/java/org/apache/druid/java/util/common/granularity/PeriodGranularity.java, core/src/main/java/org/apache/druid/math/expr/Expr.java, core/src/main/java/org/apache/druid/math/expr/ExprEval.java, processing/src/main/java/org/apache/druid/segment/filter/PredicateValueMatcherFactory.java, processing/src/main/java/org/apache/druid/segment/virtual/ExpressionSelectors.java, processing/src/test/java/org/apache/druid/segment/filter/PredicateValueMatcherFactoryTest.java, processing/src/test/java/org/apache/druid/segment/selector/TestColumnValueSelector.java, processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java
Backport of #9812 to 0.18.0-iap.
=> [Backport] Fix filtering on boolean values in transformation

docs/operations/api-reference.md, integration-tests/docker/environment-configs/coordinator, integration-tests/src/main/java/org/apache/druid/testing/clients/CompactionResourceTestClient.java, integration-tests/src/main/java/org/apache/druid/testing/clients/CoordinatorResourceTestClient.java, integration-tests/src/test/java/org/apache/druid/tests/coordinator/duty/ITAutoCompactionTest.java, server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java, server/src/main/java/org/apache/druid/server/http/CompactionResource.java, server/src/main/java/org/apache/druid/server/http/CoordinatorResource.java, server/src/test/java/org/apache/druid/server/http/security/SecurityResourceFilterTest.java, services/src/main/java/org/apache/druid/cli/CliCoordinator.java
Backport of #9644 and #9739 to 0.18.0-iap.
=> Backport auto compaction it test

core/src/main/java/org/apache/druid/timeline/partition/BuildingNumberedShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/NumberedOverwriteShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/NumberedPartialShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/NumberedShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/PartialShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/ShardSpec.java, core/src/main/java/org/apache/druid/timeline/partition/ShardSpecLookup.java, core/src/test/java/org/apache/druid/timeline/partition/BuildingNumberedShardSpecTest.java, core/src/test/java/org/apache/druid/timeline/partition/NumberedOverwriteShardSpecTest.java, indexing-service/src/main/java/org/apache/druid/indexing/common/task/LocalSegmentAllocator.java, indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/ParallelIndexSupervisorTask.java, indexing-service/src/test/java/org/apache/druid/indexing/common/task/CompactionTaskRunTest.java, indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/SinglePhaseParallelIndexingTest.java, server/src/main/java/org/apache/druid/segment/realtime/appenderator/SegmentPublisherHelper.java, server/src/main/java/org/apache/druid/segment/realtime/appenderator/TransactionalSegmentPublisher.java
Backport of #10012 to 0.18.0-iap.
=> Set the core partition set size properly for batch ingestion with dynamic partitioning

extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplier.java, extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplierTest.java
Backport https://github.com/apache/druid/pull/10062 to 0.17.0-iap
=> [BACKPORT 0.17.0-iap] retry 500 and 503 errors against kinesis

server/src/main/java/org/apache/druid/client/CachingClusteredClient.java, server/src/test/java/org/apache/druid/client/TestHttpClient.java, server/src/test/java/org/apache/druid/query/RetryQueryRunnerTest.java
Backport of #10125 to 0.19.0-iap.
=> [0.19.0-iap] Fix CachingClusteredClient when querying specific segments

processing/src/main/java/org/apache/druid/query/filter/AbstractOptimizableDimFilter.java
=> AbstractOptimizableDimFilter should be public (#10142)

jenkinsfile, pom.xml
Fixes https://implydata.atlassian.net/browse/IMPLY-3713
Created jenkinsfile for CI implementation by Jenkins pipeline
=> IMPLY-3713 jenkinsfile for Druid CI

JENKINS.md, pom.xml
Fixes https://implydata.atlassian.net/browse/IMPLY-3774
Added `JENKINS.md` with documentation about CI on Jenkins
=> IMPLY-3774 pipeline docs

web-console/src/components/json-input/json-input.tsx, web-console/src/dialogs/spec-dialog/__snapshots__/spec-dialog.spec.tsx.snap, web-console/src/dialogs/spec-dialog/spec-dialog.spec.tsx, web-console/src/dialogs/spec-dialog/spec-dialog.tsx
=> improve JSON paste (#10256)

jenkinsfile
Fixes https://implydata.atlassian.net/browse/IMPLY-3714
Added archive artifacts steps at each job
=> IMPLY-3714 use plain artifacts

benchmarks/src/test/java/org/apache/druid/benchmark/ContainsBenchmark.java, processing/src/main/java/org/apache/druid/query/filter/InDimFilter.java, processing/src/main/java/org/apache/druid/query/topn/TopNQueryBuilder.java, processing/src/main/java/org/apache/druid/segment/join/filter/JoinFilterAnalyzer.java, processing/src/test/java/org/apache/druid/segment/filter/FloatAndDoubleFilteringTest.java, processing/src/test/java/org/apache/druid/segment/filter/LongFilteringTest.java, processing/src/test/java/org/apache/druid/segment/filter/TimeFilteringTest.java
Conflicts
- constructor in processing/src/main/java/org/apache/druid/query/filter/InDimFilter.java
=> Remove NUMERIC_HASHING_THRESHOLD (#10313)

jenkinsfile
=> IMPLY-4472
