- docs/ingestion/native-batch.md
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/iterator/RangePartitionIndexTaskInputRowIteratorBuilder.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTaskTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/iterator/RangePartitionIndexTaskInputRowIteratorBuilderTest.java
Backport https://github.com/apache/incubator-druid/pull/9058 to 0.17.0-iap.
Change the behavior of parallel indexing range partitioning to fail ingestion if any row had multiple values for the partition dimension. After this change, the behavior matches that of hadoop indexing. (Previously, rows with multiple dimension values would be skipped.)
<hr>
This PR has:
> [Backport] Fail superbatch range partition multi dim values (#9058)

- extensions-contrib/distinctcount/src/test/java/org/apache/druid/query/aggregation/distinctcount/DistinctCountGroupByQueryTest.java
Backport of 9120 upstream to 0.17.0-iap
> [Backport 0.17.0-iap] Fix DistinctCountGroupByQueryTest Y2020 bug. (#9120) (#9121)

- indexing-service/src/main/java/org/apache/druid/guice/IndexingServiceTuningConfigModule.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/CompactionTask.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/IndexTask.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/ParallelIndexTuningConfig.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/ClientCompactQuerySerdeTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/CompactionTaskTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/TaskSerdeTest.java
- services/src/main/java/org/apache/druid/cli/CliIndexer.java
- services/src/main/java/org/apache/druid/cli/CliMiddleManager.java
- services/src/main/java/org/apache/druid/cli/CliOverlord.java
- services/src/main/java/org/apache/druid/cli/CliPeon.java
Backport of #9222 to 0.17.0-iap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/implydata/druid/43)
> [Backport] Support both IndexTuningConfig and ParallelIndexTuningConfig for compaction task

- licenses.yaml
- owasp-dependency-check-suppressions.xml
- pom.xml
* Suppress netty 3 vulnerabilites and upgrade netty 4 version
* Upgrade netty 4 version to fix vulnerabilities CVE-2019-20445
and CVE-2019-20444
* suppress these CVEs for netty 3
<hr>
This PR has:
Check the items by putting "x" in the brackets for the done things. Not all of these items apply to every PR. Remove the
items which are not done or not relevant to the PR. None of the items from the checklist above are strictly necessary,
but it would be very helpful if you at least self-review the PR.
<hr>
> Fix / suppress netty CVEs CVE-2019-20445 and CVE-2019-20444 (#9300)

- extensions-core/kafka-extraction-namespace/src/test/java/org/apache/druid/query/lookup/TestKafkaExtractionCluster.java
- extensions-core/kafka-indexing-service/pom.xml
- licenses.yaml
- pom.xml
Backport of https://github.com/apache/druid/pull/9259
> [Backport] fix build by updating kafka client to 2.2.2 for CVE-2019-12399

- processing/src/main/java/org/apache/druid/query/DataSource.java
- processing/src/main/java/org/apache/druid/query/QueryDataSource.java
- processing/src/main/java/org/apache/druid/query/TableDataSource.java
- processing/src/main/java/org/apache/druid/query/UnionDataSource.java
- server/src/main/java/org/apache/druid/client/CacheUtil.java
- server/src/main/java/org/apache/druid/client/CachingClusteredClient.java
- server/src/main/java/org/apache/druid/client/CachingQueryRunner.java
- server/src/test/java/org/apache/druid/client/CacheUtilTest.java
Performs backport surgery to get some cache stuff from https://github.com/apache/druid/pull/9235 to avoid the issue described in https://github.com/apache/druid/issues/8713
> [Backport] disable union query result level caching

- docs/querying/sql.md
- sql/src/main/java/org/apache/druid/sql/calcite/aggregation/builtin/GreatestSqlAggregator.java
- sql/src/main/java/org/apache/druid/sql/calcite/aggregation/builtin/LeastSqlAggregator.java
- sql/src/main/java/org/apache/druid/sql/calcite/aggregation/builtin/MultiColumnSqlAggregator.java
- sql/src/main/java/org/apache/druid/sql/calcite/planner/DruidOperatorTable.java
- sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java
* implement shell for greatest sql aggregator with hardcoded long values
* implement functional long greatest aggregator for direct access columns
* implement greatest & least sql aggregators for long & double types using abstract base class
* add javadocs, unit tests & handling for floats for greatest/least postaggregations
* minor checkstyle fix
* improve naming for the test cases
* make inner class static
* remove blank lines to retest travis build
* change trivial text to rerun travis build
* implement suggested updates for greatest/least sql aggs & fix checkstyle issues
* fix stale comments in greatest/least sql aggs abstract base
* Update sql.md
* improve sql function definitions for greatest/least sql aggs
* add more tests for greatest/least sql aggs
* add tests to cover invalid …
> [Backport] GREATEST/LEAST post-aggregators in SQL (#8719)

- LICENSE
- extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java
- extensions-core/druid-basic-security/src/test/java/org/apache/druid/security/authentication/validator/LDAPCredentialsValidatorTest.java
- licenses.yaml
- licenses/src/esapi.BSD3
Backport of https://github.com/apache/druid/pull/9600 to 0.18.0-preview
> [Backport] Fix for [CVE-2020-1958]: Apache Druid LDAP injection vulnerability (#9600)

- licenses.yaml
- pom.xml
Backport https://github.com/apache/druid/pull/9651 to 0.17.0-iap
> [Backport] Upgrade netty 4 to fix CVE-2020-11612 (#9651)

- docs/querying/groupbyquery.md
- processing/src/main/java/org/apache/druid/query/groupby/GroupByQueryConfig.java
- processing/src/test/java/org/apache/druid/query/groupby/GroupByQueryConfigTest.java
Backport of #9711 to 0.17.0-iap.
> [Backport] disable group by config applyLimitPushDownToSegment by default

- core/src/main/java/org/apache/druid/data/input/impl/CSVParseSpec.java
- core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java
- core/src/main/java/org/apache/druid/data/input/impl/JSONParseSpec.java
- core/src/main/java/org/apache/druid/data/input/impl/ParseSpec.java
- core/src/test/java/org/apache/druid/data/input/FirehoseFactoryToInputSourceAdaptorTest.java
- extensions-core/kafka-indexing-service/src/main/java/org/apache/druid/indexing/kafka/supervisor/KafkaSupervisor.java
- extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/supervisor/KinesisSupervisor.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/IndexTask.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/ParallelIndexPhaseRunner.java
- indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/ParallelIndexSupervisorTask.java
- indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskIOConfig.java
- indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java
- indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamSamplerSpec.java
- indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorIOConfig.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/CompactionTaskParallelRunTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/CompactionTaskRunTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/AbstractMultiPhaseParallelIndexingTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/AbstractParallelIndexSupervisorTaskTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/HashPartitionMultiPhaseParallelIndexingTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/batch/parallel/RangePartitionMultiPhaseParallelIndexingTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskTestBase.java
- indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/StreamChunkParserTest.java
- indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorStateTest.java
Backport of #9815 to 0.18.0-iap.
> [Backport] Remove ParseSpec.toInputFormat()

- indexing-service/src/main/java/org/apache/druid/indexing/common/task/TaskResource.java
- indexing-service/src/test/java/org/apache/druid/indexing/common/task/TaskSerdeTest.java
Clean backport of https://github.com/apache/druid/pull/9892
> [Backport] Fails creation of TaskResource if availabilityGroup is null

- licenses.yaml
- pom.xml
Backport https://github.com/apache/druid/pull/10024 to 0.18.0-iap
> [Backport] Fix CVE-2020-13602 (#10024)

- extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplier.java
- extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplierTest.java
Backport of https://github.com/apache/druid/pull/10059 to 0.16.0-iap
> [BACKPORT] retry 500 and 503 errors against kinesis

- extensions-core/kinesis-indexing-service/src/main/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplier.java
- extensions-core/kinesis-indexing-service/src/test/java/org/apache/druid/indexing/kinesis/KinesisRecordSupplierTest.java
Backport https://github.com/apache/druid/pull/10059 to 0.18.0-iap
> [BACKPORT 0.18.0-iap] retry 500 and 503 errors against kinesis #10059

- processing/src/main/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunner.java
- processing/src/test/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunnerTest.java
- server/src/main/java/org/apache/druid/server/ClientQuerySegmentWalker.java
- server/src/main/java/org/apache/druid/server/coordination/ServerManager.java
- server/src/test/java/org/apache/druid/server/coordination/ServerManagerTest.java
Backport of #10199 to 0.19.0-iap.
> [0.19.0-iap] Report missing segments when there is no segment for the query datasource in historicals

- processing/src/main/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunner.java
- processing/src/test/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunnerTest.java
- server/src/main/java/org/apache/druid/server/ClientQuerySegmentWalker.java
- server/src/main/java/org/apache/druid/server/coordination/ServerManager.java
- server/src/test/java/org/apache/druid/server/coordination/ServerManagerTest.java
Backport of #10199 to 0.18.0-iap.
> [0.18.0-iap] Report missing segments when there is no segment for the query datasource in historicals

- core/src/main/java/org/apache/druid/indexer/TaskLocation.java
- integration-tests/src/main/java/org/apache/druid/testing/utils/AbstractTestQueryHelper.java
- integration-tests/src/main/java/org/apache/druid/testing/utils/SqlTestQueryHelper.java
- integration-tests/src/main/java/org/apache/druid/testing/utils/TestQueryHelper.java
- server/src/main/java/org/apache/druid/discovery/DiscoveryDruidNode.java
- sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java
- sql/src/test/java/org/apache/druid/sql/calcite/schema/SystemSchemaTest.java
Backport of #10183 to 0.19.0-iap.
> [0.19.0-iap] Fix sys.servers table to not throw NPE and handle brokers/indexers/peons properly for broadcast segments

- processing/src/main/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunner.java
- processing/src/test/java/org/apache/druid/query/ReportTimelineMissingSegmentQueryRunnerTest.java
- server/src/main/java/org/apache/druid/server/coordination/ServerManager.java
- server/src/test/java/org/apache/druid/server/coordination/ServerManagerTest.java
Backport of #10199 to 0.17.0-iap.
> [0.17.0-iap] Report missing segments when there is no segment for the query datasource in historicals

- processing/src/main/java/org/apache/druid/query/timeseries/TimeseriesQuery.java
- processing/src/main/java/org/apache/druid/query/timeseries/TimeseriesQueryQueryToolChest.java
- processing/src/test/java/org/apache/druid/query/groupby/GroupByTimeseriesQueryRunnerTest.java
- processing/src/test/java/org/apache/druid/query/timeseries/TimeseriesQueryRunnerTest.java
- sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java
Backport of #10198 to 0.19.0-iap.
> [0.19.0-iap] Fix timeseries query constructor when postAggregator has an expression reading timestamp result column

- processing/src/main/java/org/apache/druid/query/groupby/GroupByQuery.java
- processing/src/test/java/org/apache/druid/query/groupby/GroupByQueryRunnerTest.java
- processing/src/test/java/org/apache/druid/query/groupby/GroupByQueryTest.java
- sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java
Backport of #10253 to 0.19.0-iap.
> [0.19.0-iap] Allow forceLimitPushDown in SQL
